version: "3.9"

services:
  db:
    image: postgres:13
    container_name: scholl_db
    environment:
      POSTGRES_DB: scholl_db
      POSTGRES_USER: scholl_user
      POSTGRES_PASSWORD: scholl_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  web:
    build: .
    container_name: scholl_web
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      # Configuración base de datos
      POSTGRES_DB: scholl_db
      POSTGRES_USER: scholl_user
      POSTGRES_PASSWORD: scholl_password
      DB_HOST: db
      DB_PORT: 5432

      # Datos del superusuario automático
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      DJANGO_SUPERUSER_PASSWORD: admin123
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
